### ISSUE TITLE
How could you get more than 1K sps ?

### ISSUE THREAD

**Issue by ortegafernando** [ControlEverythingCommunity/ADC121C021#1]
Hi, 

The example that you have for arduino, includes a `delay(300);` that makes it to get only 3 o 4 samples per second.

How much we can reduce that delay? Eliminate? How could you get 188.000 samples per second? May be with 10k or 30k it is ok, but with that DELAY, it is imposible.

hope your answer.

**Comment by ryker1990** [comment]
The delay provided is to ensure that arduino has the data ready before a read attempt is made.
Its not a constraint , you can reduce it to 10ms , if the output data  is correct. 
With 10ms you can get 100 samples / sec.

**Comment by ortegafernando** [comment]
Hi, for monitoring a 50-60Hz AC wave 100 samples is poor. Have you got any experiencie deleting that delay ? Or may be: 10uS or 50uS ?

**Comment by ryker1990** [comment]
You can remove the delay and see what happens . This code  is a generic sample and you can modify it according to your requirements. Change and see , what happens .. :)

**Comment by ortegafernando** [comment]
Hi, thanks. The problem is that I still haven't got the IC to check it. If anybody could check .... greets !!!

Regardss
